# Generated by Django 3.0.4 on 2020-08-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scomp', '0009_packagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('flat', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('Area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.ServiceModel')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.SubServiceModel')),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.UserRegistrationModel')),
            ],
        ),
    ]
