# Generated by Django 3.0.4 on 2020-08-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='professionaldatamodel',
            name='street',
        ),
    ]
