# Generated by Django 3.0.4 on 2020-08-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0009_packagemodel_image'),
        ('ProfessionalApp', '0002_auto_20200816_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldatamodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scomp.ServiceModel'),
        ),
        migrations.AlterField(
            model_name='professionaldatamodel',
            name='subservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scomp.SubServiceModel'),
        ),
    ]
