# Generated by Django 3.0.4 on 2020-08-16 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0009_packagemodel_image'),
        ('ProfessionalApp', '0003_auto_20200816_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalRatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
                ('total', models.IntegerField()),
                ('avrage', models.IntegerField()),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.UserRegistrationModel')),
            ],
        ),
    ]
