# Generated by Django 3.0.4 on 2020-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApp', '0004_professionalratingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalratingmodel',
            name='avrage',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
