# Generated by Django 3.0.4 on 2020-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfessionalApp', '0005_auto_20200816_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalratingmodel',
            name='avrage',
            field=models.CharField(max_length=3),
        ),
    ]
