# Generated by Django 3.0.4 on 2020-08-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0009_packagemodel_image'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.UserRegistrationModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.UserRegistrationModel')),
            ],
        ),
    ]
