# Generated by Django 3.0.4 on 2020-08-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0010_timeslotmodel'),
        ('UserApp', '0003_auto_20200814_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=36)),
                ('profid', models.CharField(max_length=36, null=True)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('paymode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.PackageModel')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.TimeSlotModel')),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scomp.UserRegistrationModel')),
            ],
        ),
    ]
