# Generated by Django 3.0.4 on 2020-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='amount',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
    ]
