# Generated by Django 3.0.4 on 2020-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_ordermodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ratingflag',
            field=models.IntegerField(default=0),
        ),
    ]
