# Generated by Django 3.0.4 on 2020-08-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0002_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dataselector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='workImagesFolder')),
                ('workselector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scomp.WorkModel')),
            ],
        ),
    ]
