# Generated by Django 3.0.4 on 2020-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0003_workimagemodel_workmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
