# Generated by Django 3.0.4 on 2020-08-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0004_customerformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parentservice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scomp.ServiceModel')),
            ],
        ),
    ]
