# Generated by Django 3.0.4 on 2020-08-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0005_subservicemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservicemodel',
            name='parentservice',
        ),
    ]
