# Generated by Django 3.0.4 on 2020-08-12 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0006_remove_subservicemodel_parentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicemodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scomp.ServiceModel'),
        ),
    ]
