# Generated by Django 3.0.4 on 2020-08-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0007_subservicemodel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('offer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TermModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('details', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('offername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scomp.OfferModel')),
                ('packagetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scomp.PackageTypeModel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scomp.ServiceModel')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scomp.SubServiceModel')),
            ],
        ),
    ]
