# Generated by Django 3.0.4 on 2020-08-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0009_packagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
            ],
        ),
    ]
