# Generated by Django 3.0.4 on 2020-08-18 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0010_timeslotmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerformmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
