# Generated by Django 3.0.4 on 2020-08-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scomp', '0011_customerformmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('ndate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
